# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 02:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_user_photourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='created',
        ),
    ]
