# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_remove_media_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='created',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
